<?php
/**
 * MarKor NET
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   MarKorNET
 * @package    MarKor_QuickInfo
 * @author     Marcin Korzystka  <support@markornet.com>
 * @copyright  Copyright (c) MarKor NET (http://www.markornet.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
$storePhone = Mage::getStoreConfig('general/store_information/phone');
$storeEmail = Mage::getStoreConfig('trans_email/ident_general/email');
?>
<div class="quickinfo">
<div class="block-title"><strong><?php echo $this->__('Contact Us'); ?></strong></div>
<p><?php echo $storePhone; ?></p>
<p><?php echo $storeEmail; ?></p>
</div>
